branch-defaults:
  eb:
    environment: Ifvent-craftingsuccess-env
environment-defaults:
  Ifvent-craftingsuccess-env:
    branch: null
    repository: null
global:
  application_name: ifvent-craftingsuccess
  branch: null
  default_ec2_keyname: null
  default_platform: PHP 8.1 running on 64bit Amazon Linux 2
  default_region: ap-southeast-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
